os: osx
language: swift
osx_image: xcode10.2
xcode_project: JNGradientLabel.xcodeproj

env:
  - DESTINATION='platform=iOS Simulator,OS=9.3,name=iPhone 5s'
  - DESTINATION='platform=iOS Simulator,OS=10.0,name=iPhone 5s'
  - DESTINATION='platform=iOS Simulator,name=iPhone XS Max'

script:
  - set -o pipefail && travis_retry xcodebuild -scheme JNGradientLabel -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES
